POST {{ host }}/customers

{
    "name": "Aarón Nadal",
    "email": "email@demo.com",
    "address": {
        "address": "Main Street, 6",
        "city": "New London",
        "postalCode": "12345"
    }
}
