PUT {{ host }}/customers/787da459-b906-47f3-bcef-cb22436358de

{
    "name": "John Doe",
    "email": "john.doe@demo.com",
    "address": {
        "address": "Main Street, 16",
        "city": "Old London",
        "postalCode": "54321"
    }
}
