PUT {{ host }}/customers/64f225dd-16fd-42d2-8833-412d89b3744c

{
    "name": "John Doe",
    "email": "john.doe@demo.com",
    "address": {
        "address": "Main Street, 16",
        "city": "Old London",
        "postalCode": "54321"
    }
}
